In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [4]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
import math
median_bedrooms= math.floor(df.bedrooms.median())
median_bedrooms

4

In [7]:
df.bedrooms.fillna(median_bedrooms)

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [8]:
df['bedrooms']= df.bedrooms.fillna(median_bedrooms)

In [9]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [10]:
reg= linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']], df.price)

LinearRegression()

In [16]:
import math
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [12]:
reg.predict([[2600,3.0,20]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([518217.63297611])

EXERCISE

In [39]:
df= pd.read_csv('hiring.csv')
df.head(10)

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [21]:
!pip install word2number

  Preparing metadata (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5566 sha256=a314cf82ce7b304bfb44e590b88ecb7e4c02d138801cdddbd9920c9a51d67970
  Stored in directory: /root/.cache/pip/wheels/84/ff/26/d3cfbd971e96c5aa3737ecfced81628830d7359b55fbb8ca3b
Successfully built word2number


In [22]:
from word2number import w2n

In [43]:
df.experience=df.experience.fillna('zero')


In [44]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [45]:
df.experience.value_counts()

experience
zero      2
five      1
two       1
seven     1
three     1
ten       1
eleven    1
Name: count, dtype: int64

In [46]:
df['experience'].dtypes

dtype('O')

In [48]:
df['experience'] = df.experience.apply(w2n.word_to_num)

In [52]:
df.head()


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000

In [55]:
df.isna().value_counts()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
False       False                  False                       False        7
            True                   False                       False        1
Name: count, dtype: int64

In [58]:
import math
mean_test_score= math.floor(df['test_score(out of 10)'].mean())
mean_test_score

7

In [60]:
df['test_score(out of 10)']= df['test_score(out of 10)'].fillna(mean_test_score)
df.head(10)

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [61]:
model= linear_model.LinearRegression()
model.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [62]:
model.predict([[2,9,6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])